# https://www.appveyor.com/docs/appveyor-yml/

# Test against these versions of Node.js.
environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "10"
    - nodejs_version: "12"

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version

cache:
  - '%LOCALAPPDATA%\Yarn'

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - git rev-parse HEAD
  - cmd: yarn run test

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"
